### ISSUE TITLE
推理代码是K024/ChatGLM-6b-onnx-u8s8中的web-ui.py吗？

### ISSUE THREAD

**Issue by YueWen1024** [K024/chatglm-q#1]
您好，看到您在readme中写道: The inference code is packed in the huggingface hub，请问推理代码是K024/ChatGLM-6b-onnx-u8s8中的web-ui.py吗？

**Comment by K024** [comment]
只有 onnx 模型的推理不在这个repo下，torch 的模型推理就照 usage 部分

**Comment by YueWen1024** [comment]
> 只有 onnx 模型的推理不在这个repo下，torch 的模型推理就照 usage 部分

感谢回复，请问onnx 模型要怎么推理呢？

**Comment by K024** [comment]
onnx 推理就用你标题里那个文件

**Comment by YueWen1024** [comment]
> onnx 推理就用你标题里那个文件

嗯嗯好的，感谢指导

**Comment by xxllp** [comment]
不知道转onnx后模型的效果是否差别会比较大
